# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load Air DataFrame

In [8]:
df=pd.read_excel("AirQualityUCI.xlsx",na_values="-200")
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.00,150,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.25,112,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.00,88,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.50,80,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.25,51,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794

# Data Cleaning(Handling Missing Values)

In [15]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [14]:
for column in df.drop(["Date","Time"],axis=1).columns:
    df[column]=df[column].fillna(df[column].median())

## MAKING CO MY TARGET

In [30]:
# Convert the 'time' column to datetime (with only time information)
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')

# Extract the hour using .dt accessor
df['Hour'] = df['Time'].dt.hour

df["Date"]=pd.to_datetime(df["Date"])

df["Day"]=df["Date"].dt.day

df["Month"]=df["Date"].dt.month

In [33]:
df=df.drop(["Date","Time"],axis=1)

In [35]:
df.corr()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Hour,Day,Month
CO(GT),1.000000,0.776959,0.174974,0.809010,0.795978,0.780505,-0.619329,0.656163,0.548470,0.763531,0.005966,0.041100,0.022863,0.329461,0.000360,0.087442
PT08.S1(CO),0.776959,1.000000,0.247551,0.883905,0.892996,0.622606,-0.770514,0.563595,0.682361,0.899419,0.049020,0.114421,0.135726,0.320457,-0.018631,-0.038327
NMHC(GT),0.174974,0.247551,1.000000,0.135401,0.132763,-0.091697,0.051803,-0.012326,0.210915,0.110387,-0.067027,-0.014157,-0.121803,0.049371,0.063571,-0.230206
C6H6(GT),0.809010,0.883905,0.135401,1.000000,0.981633,0.616363,-0.733513,0.533687,0.764612,0.865758,0.199257,-0.061747,0.168411,0.335804,-0.011110,0.125958
PT08.S2(NMHC),0.795978,0.892996,0.132763,0.981633,1.000000,0.606237,-0.795768,0.562180,0.776953,0.880645,0.241533,-0.090409,0.187167,0.380565,-0.019698,0.125115
NOx(GT),0.780505,0.622606,-0.091697,0.616363,0.606237,1.000000,-0.572460,0.760738,0.200840,0.694866,-0.245858,0.183844,-0.148301,0.213536,-0.024542,0.104709
PT08.S3(NOx),-0.619329,-0.770514,0.051803,-0.733513,-0.795768,-0.572460,1.000000,-0.574249,-0.538401,-0.795316,-0.144791,-0.056798,-0.231595,-0.317044,0.025700,-0.059215
NO2(GT),0.656163,0.563595,-0.012326,0.533687,0.562180,0.760738,-0.574249,1.000000,0.140267,0.630555,-0.169315,-0.082253,-0.297994,0.331580,-0.016083,-0.167034
PT08.S4(NO2),0.548470,0.682361,0.210915,0.764612,0.776953,0.200840,-0.538401,0.140267,1.000000,0.590764,0.561236,-0.032174,0.629515,0.216618,-0.039685,0.171203
PT08.S5(O3),0.763531,0.899419,0.110387,0.865758,0.880645,0.694866,-0.795316,0.630555,0.590764,1.000000,-0.026805,0.124789,0.071135,0.239377,-0.030986,0.048352
T,0.005966,0.049020,-0.067027,0.199257,0.241533,-0.245858,-0.144791,-0.169315,0.561236,-0.026805,1.000000,-0.578564,0.656534,0.202012,-0.032141,0.275201
RH,0.041100,0.114421,-0.014157,-0.061747,-0.090409,0.183844,-0.056798,-0.082253,-0.032174,0.124789,-0.578564,1.000000,0.167898,-0.289528,-0.019059,0.080118
AH,0.022863,0.135726,-0.121803,0.168411,0.187167,-0.148301,-0.231595,-0.297994,0.629515,0.071135,0.656534,0.167898,1.000000,-0.018431,-0.070166,0.414068
Hour,0.329461,0.320457,0.049371,0.335804,0.380565,0.213536,-0.317044,0.331580,0.216618,0.239377,0.202012,-0.289528,-0.018431,1.000000,0.000849,-0.000102
Day,0.000360,-0.018631,0.063571,-0.011110,-0.019698,-0.024542,0.025700,-0.016083,-0.039685,-0.030986,-0.032141,-0.019059,-0.070166,0.000849,1.000000,-0.010046
Month,0.087442,-0.038327,-0.230206,0.125958,0.125115,0.104709,-0.059215,-0.167034,0.171203,0.048352,0.275201,0.080118,0.414068,-0.000102,-0.010046,1.000000

In [48]:
X=df.drop(["T","RH","AH","Day","Month","CO(GT)"],axis=1)
y=df["CO(GT)"]

In [41]:
df.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Hour,Day,Month
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,2.089302,1098.272025,-159.090093,10.010899,937.854610,235.131100,834.202567,112.360329,1456.401901,1020.452175,18.293913,49.244785,1.024351,11.498557,15.876884,6.310356
std,1.323024,212.915093,139.789093,7.311212,261.622644,195.093027,251.808390,43.938455,339.367768,390.779481,8.659092,16.974420,0.395879,6.923182,8.808653,3.438160
min,0.100000,647.250000,-200.000000,0.149048,383.250000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.175000,0.184679,0.000000,1.000000,1.000000
25%,1.200000,941.250000,-200.000000,4.591495,742.500000,112.000000,665.500000,85.900000,1241.500000,741.750000,12.025000,36.550000,0.746115,5.000000,8.000000,3.000000
50%,1.800000,1063.000000,-200.000000,8.239851,909.000000,179.800000,805.500000,109.000000,1462.750000,963.250000,17.750000,49.550000,0.995395,11.000000,16.000000,6.000000
75%,2.600000,1221.250000,-200.000000,13.636091,1104.750000,284.200000,960.250000,133.000000,1662.000000,1255.250000,24.075000,61.875000,1.296223,18.000000,23.000000,9.000000
max,11.900000,2039.750000,1189.000000,63.741476,2214.000000,1479.000000,2682.750000,339.700000,2775.000000,2522.750000,44.600000,88.725000,2.231036,23.000000,31.000000,12.000000

In [49]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3)

In [51]:
columns_to_scale=X.columns[X.columns !="Hour"]
columns_to_scale

Index(['PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)',
       'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)'],
      dtype='object')

In [52]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

pipe=Pipeline([
    ("scaler",StandardScaler()),
    ("poly",PolynomialFeatures(degree=2)),
    ("model",LinearRegression())
])

pipe.fit(X_train,y_train)
pipe.score(X_test,y_test)

0.8618422874295061

In [56]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
pipe=Pipeline([
    ("scaler",StandardScaler()),
    ("poly",PolynomialFeatures(degree=2)),
    ("model",BaggingRegressor(estimator=DecisionTreeRegressor()))
])

pipe.fit(X_train,y_train)
pipe.score(X_test,y_test)

0.8758112300176242

In [61]:
from xgboost import XGBRegressor

pipe=Pipeline([
    ("scaler",StandardScaler()),
    ("poly",PolynomialFeatures(degree=2)),
    ("model",XGBRegressor())
])
pipe.fit(X_train,y_train)
pipe.score(X_test,y_test)

0.8847144068454579