In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
df = pd.read_csv("MathE dataset (4).csv", delimiter=";", encoding="ISO-8859-1")
df

,Student ID,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords
0,647,Ireland,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
1,41,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
2,340,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
3,641,Italy,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
4,669,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
...,...,...,...,...,...,...,...,...
9541,175,Italy,1497,1,Basic,Complex Numbers,Complex Numbers,"Imaginary part,Conjugate number,Modulus of a c..."
9542,175,Italy,1514,0,Basic,Complex Numbers,Complex Numbers,Operations with complex numbers
9543,175,Italy,1521,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Quadratic equations,Simplify expressions,Linea..."
9544,175,Italy,1526,1,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Linear equations,Quadratic equations,Simplify ..."
9545,175,Italy,1549,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Simplify expressions,Linear equations,Quadrati..."

## Data Evaluation and Preperation

In [15]:
df.isna().sum()

Student ID         0
Student Country    0
Question ID        0
Type of Answer     0
Question Level     0
Topic              0
Subtopic           0
Keywords           0
dtype: int64

In [16]:
df=df.drop("Student ID",axis=1)
df

,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords
0,Ireland,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
1,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
2,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
3,Italy,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
4,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
...,...,...,...,...,...,...,...
9541,Italy,1497,1,Basic,Complex Numbers,Complex Numbers,"Imaginary part,Conjugate number,Modulus of a c..."
9542,Italy,1514,0,Basic,Complex Numbers,Complex Numbers,Operations with complex numbers
9543,Italy,1521,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Quadratic equations,Simplify expressions,Linea..."
9544,Italy,1526,1,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Linear equations,Quadratic equations,Simplify ..."
9545,Italy,1549,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Simplify expressions,Linear equations,Quadrati..."

In [19]:
df["Type of Answer"].value_counts()

Type of Answer
0    5076
1    4470
Name: count, dtype: int64

In [20]:
X=df.drop("Type of Answer",axis=1)
y=df["Type of Answer"]
X=pd.get_dummies(X)

In [21]:
X

,Question ID,Student Country_Ireland,Student Country_Italy,Student Country_Lithuania,Student Country_Portugal,Student Country_Romania,Student Country_Russian Federation,Student Country_Slovenia,Student Country_Spain,Question Level_Advanced,...,Keywords_Trigonometric substitution,"Keywords_Trigonometric substitution,Simple integration","Keywords_Unconstrained optimization,Second derivative test,Optimal solution","Keywords_Undetermined solution of linear system,Consistent system,Inconsistent system,Solution of linear system","Keywords_Undetermined solution of linear system,Consistent system,Square linear system,Inconsistent system,Solution of linear system","Keywords_Union of sets,Venn diagram,Complement of a set","Keywords_Volume of revolution,Fundamental theorem of Calculus","Keywords_y-simple region (type I),Area ,Cartesian coordinates","Keywords_y-simple region (type I),Cartesian coordinates,Area ,Iterate integrals","Keywords_y-simple region (type I),Cartesian coordinates,Iterate integrals"
0,77,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,77,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,77,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,77,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,77,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9541,1497,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9542,1514,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9543,1521,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9544,1526,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9545,1549,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Model Selection And Training

In [22]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [23]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression