In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [24]:
df = pd.read_csv("MathE dataset (4).csv", delimiter=";", encoding="ISO-8859-1")
df

,Student ID,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords
0,647,Ireland,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
1,41,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
2,340,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
3,641,Italy,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
4,669,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
...,...,...,...,...,...,...,...,...
9541,175,Italy,1497,1,Basic,Complex Numbers,Complex Numbers,"Imaginary part,Conjugate number,Modulus of a c..."
9542,175,Italy,1514,0,Basic,Complex Numbers,Complex Numbers,Operations with complex numbers
9543,175,Italy,1521,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Quadratic equations,Simplify expressions,Linea..."
9544,175,Italy,1526,1,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Linear equations,Quadratic equations,Simplify ..."
9545,175,Italy,1549,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Simplify expressions,Linear equations,Quadrati..."

## Data Evaluation Preperation And Feature Engineering

In [25]:
df.isna().sum()

Student ID         0
Student Country    0
Question ID        0
Type of Answer     0
Question Level     0
Topic              0
Subtopic           0
Keywords           0
dtype: int64

In [26]:
df=df.drop("Student ID",axis=1)
df

,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords
0,Ireland,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
1,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
2,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
3,Italy,77,0,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
4,Portugal,77,1,Basic,Statistics,Statistics,"Stem and Leaf diagram,Relative frequency,Sampl..."
...,...,...,...,...,...,...,...
9541,Italy,1497,1,Basic,Complex Numbers,Complex Numbers,"Imaginary part,Conjugate number,Modulus of a c..."
9542,Italy,1514,0,Basic,Complex Numbers,Complex Numbers,Operations with complex numbers
9543,Italy,1521,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Quadratic equations,Simplify expressions,Linea..."
9544,Italy,1526,1,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Linear equations,Quadratic equations,Simplify ..."
9545,Italy,1549,0,Basic,Fundamental Mathematics,"Algebraic expressions, Equations, and Inequali...","Simplify expressions,Linear equations,Quadrati..."

In [27]:
df["Type of Answer"].value_counts()

Type of Answer
0    5076
1    4470
Name: count, dtype: int64

In [64]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()
X=df.drop(["Type of Answer","Keywords","Question ID"],axis=1)
y=df["Type of Answer"]
v=vector.fit_transform(df.Keywords)
df_v=pd.DataFrame(v.toarray(),columns=vector.get_feature_names_out())
X=pd.get_dummies(X,drop_first=True)

In [65]:
X=pd.concat([X,df_v],axis=1)
X

,Student Country_Italy,Student Country_Lithuania,Student Country_Portugal,Student Country_Romania,Student Country_Russian Federation,Student Country_Slovenia,Student Country_Spain,Question Level_Basic,Topic_Complex Numbers,Topic_Differential Equations,...,trigonometric,type,unconstrained,undetermined,union,variables,variance,venn,volume,with
0,False,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
1,False,False,True,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
2,False,False,True,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
3,True,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
4,False,False,True,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9541,True,False,False,False,False,False,False,True,True,False,...,0,0,0,0,0,0,0,0,0,0
9542,True,False,False,False,False,False,False,True,True,False,...,0,0,0,0,0,0,0,0,0,1
9543,True,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
9544,True,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0
9545,True,False,False,False,False,False,False,True,False,False,...,0,0,0,0,0,0,0,0,0,0

## Model Selection And Training

In [22]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [51]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [66]:
fold=StratifiedKFold(n_splits=6,shuffle=True,random_state=42)
models=[MultinomialNB(),RandomForestClassifier(),LogisticRegression()]
for i in models:
    cvs=cross_val_score(i,X,y,cv=fold)
    print({"model":i,"score":cvs})

{'model': MultinomialNB(), 'score': array([0.56945317, 0.56756757, 0.55185418, 0.55499686, 0.55373979,
       0.54934004])}
{'model': RandomForestClassifier(), 'score': array([0.5876807 , 0.57259585, 0.59208045, 0.56568196, 0.58328096,
       0.59396606])}

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

{'model': LogisticRegression(), 'score': array([0.57259585, 0.56568196, 0.57071025, 0.57385292, 0.57888121,
       0.59270899])}

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [62]:
X

,Question ID,Student Country_Italy,Student Country_Lithuania,Student Country_Portugal,Student Country_Romania,Student Country_Russian Federation,Student Country_Slovenia,Student Country_Spain,Question Level_Basic,Topic_Complex Numbers,...,Keywords_Trigonometric substitution,"Keywords_Trigonometric substitution,Simple integration","Keywords_Unconstrained optimization,Second derivative test,Optimal solution","Keywords_Undetermined solution of linear system,Consistent system,Inconsistent system,Solution of linear system","Keywords_Undetermined solution of linear system,Consistent system,Square linear system,Inconsistent system,Solution of linear system","Keywords_Union of sets,Venn diagram,Complement of a set","Keywords_Volume of revolution,Fundamental theorem of Calculus","Keywords_y-simple region (type I),Area ,Cartesian coordinates","Keywords_y-simple region (type I),Cartesian coordinates,Area ,Iterate integrals","Keywords_y-simple region (type I),Cartesian coordinates,Iterate integrals"
0,77,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,77,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,77,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,77,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,77,False,False,True,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9541,1497,True,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
9542,1514,True,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
9543,1521,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
9544,1526,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
9545,1549,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False