In [3]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd
  
# fetch dataset 
heart_disease = fetch_ucirepo(id=45)

In [4]:
heart_disease.data.features

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0

In [5]:
heart_disease.data.targets

     num
0      0
1      2
2      1
3      0
4      0
..   ...
298    1
299    2
300    3
301    1
302    0

[303 rows x 1 columns]

In [6]:
df=heart_disease.data.original
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0

In [7]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000,301.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241,4.734219,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438,1.939706,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,7.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,4.000000

In [8]:
df["ca"]=df["ca"].fillna(df["ca"].median())
df["thal"]=df["thal"].fillna(df["thal"].median())

In [9]:
X=df.drop("num",axis=1)
y=df["num"]

## TRAINING WITH THE LOGISTIC MODEL

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.25)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model=LogisticRegression(max_iter=1000,C=0.1)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.76      0.95      0.84        39
           1       0.60      0.20      0.30        15
           2       0.38      0.30      0.33        10
           3       0.21      0.38      0.27         8
           4       0.00      0.00      0.00         4

    accuracy                           0.61        76
   macro avg       0.39      0.36      0.35        76
weighted avg       0.58      0.61      0.56        76

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## TRAINING WITH DECISIION TREES

In [12]:
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.69      0.69      0.69        39
           1       0.31      0.33      0.32        15
           2       0.27      0.30      0.29        10
           3       0.22      0.25      0.24         8
           4       0.00      0.00      0.00         4

    accuracy                           0.49        76
   macro avg       0.30      0.32      0.31        76
weighted avg       0.48      0.49      0.48        76

## TRAINING WITH LOGISTIC REGRESSION AND ALSO PIPELINE SCALING

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

pipe_model=Pipeline([
    ("scaler",StandardScaler()),
    ("model",LogisticRegression(C=0.1))
])

pipe_model.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(C=0.1))])

In [14]:
y_pred=pipe_model.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.73      0.90      0.80        39
           1       0.40      0.13      0.20        15
           2       0.14      0.10      0.12        10
           3       0.25      0.50      0.33         8
           4       0.00      0.00      0.00         4

    accuracy                           0.55        76
   macro avg       0.30      0.33      0.29        76
weighted avg       0.50      0.55      0.50        76

C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [15]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.74      0.90      0.81        39
           1       0.09      0.07      0.08        15
           2       0.11      0.10      0.11        10
           3       0.12      0.12      0.12         8
           4       0.00      0.00      0.00         4

    accuracy                           0.50        76
   macro avg       0.21      0.24      0.22        76
weighted avg       0.43      0.50      0.46        76

In [16]:
df.num.value_counts()

num
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

In [33]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek

rus=RandomUnderSampler()
smotek=SMOTETomek()
X_rus,y_rus=rus.fit_resample(X_train,y_train)
X_train_smotek,y_train_smotek=smotek.fit_resample(X_train,y_train)
y_rus.value_counts()

num
0    102
1    102
Name: count, dtype: int64

In [34]:
model=LogisticRegression(C=0.01,max_iter=1000)
model.fit(X_rus,y_rus)

y_pred=model.predict(X_test)
score=classification_report(y_test,y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.82      0.82      0.82        39
           1       0.81      0.81      0.81        37

    accuracy                           0.82        76
   macro avg       0.82      0.82      0.82        76
weighted avg       0.82      0.82      0.82        76

In [35]:
model=LogisticRegression(C=0.01,max_iter=1000)
model.fit(X_train_smotek,y_train_smotek)

y_pred=model.predict(X_test)
score=classification_report(y_test,y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.79      0.77      0.78        39
           1       0.76      0.78      0.77        37

    accuracy                           0.78        76
   macro avg       0.78      0.78      0.78        76
weighted avg       0.78      0.78      0.78        76

In [36]:
model=DecisionTreeClassifier(criterion="gini",)
model.fit(X_train_smotek,y_train_smotek)
y_pred=model.predict(X_test)
score=classification_report(y_test,y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.81      0.77      0.79        39
           1       0.77      0.81      0.79        37

    accuracy                           0.79        76
   macro avg       0.79      0.79      0.79        76
weighted avg       0.79      0.79      0.79        76

In [37]:
from sklearn.svm import SVC

model=SVC(kernel="rbf",C=4.00001)
model.fit(X_train_smotek,y_train_smotek)
y_pred=model.predict(X_test)
score=classification_report(y_test,y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.66      0.64      0.65        39
           1       0.63      0.65      0.64        37

    accuracy                           0.64        76
   macro avg       0.64      0.64      0.64        76
weighted avg       0.65      0.64      0.64        76

## Preprocessing Target

In [24]:
df["num"]=df["num"].map({1:1,2:1,3:1,4:1,0:0})

In [25]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0,1
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,0.0,3.0,0

In [26]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

In [27]:
X=df.drop("num",axis=1)
y=df.num

In [29]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.25)

In [31]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression(C=0.01)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
score=classification_report(y_test,y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.82      0.92      0.87        39
           1       0.91      0.78      0.84        37

    accuracy                           0.86        76
   macro avg       0.86      0.85      0.85        76
weighted avg       0.86      0.86      0.85        76

C:\Users\user\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
from xgboost import xgboost